### ISSUE TITLE
*-ssl.mzstatic.com breaking Apple's AppStore

### ISSUE THREAD

**Issue by holdit** [d43m0nhLInt3r/socialblocklists#1]
There are a few entries on the TikTok list that blocks legit Apple content and doesn't seem to be used by the app:

`*-ssl.mzstatic.com`

If I had to guess, the person that created this list uses iOS and the App Store made some requests in the background while TikTok was being used.

The result is (some) images missing on their site/store app:

<img width="1042" alt="Screenshot 2020-03-30 at 01 30 25" src="https://user-images.githubusercontent.com/23439751/77865448-55add200-7226-11ea-9913-60e63def3880.png">

**Comment by d43m0nhLInt3r** [comment]
thx for the info i will change it ^^

**Comment by d43m0nhLInt3r** [comment]
changed it:
https://github.com/d43m0nhLInt3r/socialblocklists/commit/db2a1ca6855abe763a8e3508bc5764c8c9a2e670
