### ISSUE TITLE
ghostery.com

### ISSUE THREAD

**Issue by p1r473** [d43m0nhLInt3r/socialblocklists#11]
This is a privacy browser plugin that protects you from trackers

**Comment by d43m0nhLInt3r** [comment]
which list?

**Comment by d43m0nhLInt3r** [comment]
found it and [fixed it](https://github.com/d43m0nhLInt3r/socialblocklists/commit/3cc3d456db488a0e51e5817e02b5f60e7ee24a75) thanks!
