### ISSUE TITLE
mi.edgekey.net , edgekey.net 

### ISSUE THREAD

**Issue by p1r473** [d43m0nhLInt3r/socialblocklists#22]
mi.edgekey.net, edgekey.net  is a false positive

edgekey.net is a domain that is owned and used by Akamai that is primarily used for website acceleration through the Akamai CDN. Content Delivery Networks (CDNs) put website content on servers that are spread throughout the world.

its also a CNAME for several sites such as miamiherald.com.

**Comment by d43m0nhLInt3r** [comment]
fixed f402b70
