### ISSUE TITLE
pie_hole gravity error

### ISSUE THREAD

**Issue by error13** [d43m0nhLInt3r/socialblocklists#23]
[i] Target: https://github.com/d43m0nhLInt3r/socialblocklists/blob/master/Facebook/facebookblocklist.txt
  [✓] Status: Retrieval successful
  [i] Received 2 domains, 2 domains invalid!
      Sample of invalid domains:
      - content="github.com">
      - content="github.com">

**Comment by d43m0nhLInt3r** [comment]
You need to use the raw format since you point to a html file and not a text file: https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/Facebook/facebookblocklist.txt

**Comment by error13** [comment]
yes i already i figured that out sorry for opening a issue thanks for sharing your list
