### ISSUE TITLE
Pi-Hole blocks facebook completely

### ISSUE THREAD

**Issue by dvdvideo1234** [d43m0nhLInt3r/socialblocklists#26]

**Comment by d43m0nhLInt3r** [comment]
I need more information. Which blocklist do you use?

**Comment by dvdvideo1234** [comment]
https://github.com/d43m0nhLInt3r/socialblocklists/tree/master/Facebook

**Comment by d43m0nhLInt3r** [comment]
This block list is intended to completely block Facebook.
