### ISSUE TITLE
Commit 2173c5d blocks YOUTUBE completely - not only ads on youtube

### ISSUE THREAD

**Issue by thomasmerz** [d43m0nhLInt3r/socialblocklists#30]
Commit https://github.com/d43m0nhLInt3r/socialblocklists/commit/2173c5d53d7402994761e775c135531e6312acdc does not only block ads from youtube - it disables youtube completely as my family told me (no youtube since xmas until I found time to have a deeper look today :-(
Sorry, but this makes your "youtube ads blocker" total unusable, because this was shooting beyond the target.
Please fix/revert this.

**Comment by d43m0nhLInt3r** [comment]
This blocklist is supposed to block Youtube. But I will try to create a Youtube advertising blocklist and upload it over the next few days.

I thank you for your support

**Comment by thomasmerz** [comment]
Ok, that's fine for me, when THIS list will change its purpose and if we (the community) will get a new list to block only ads on youtube 👍🏻

**Comment by d43m0nhLInt3r** [comment]
Here is the new Youtube Ad Blocklist a5bccd6. I just forked it because it is difficult to block the right servers.

**Comment by thomasmerz** [comment]
Ok, let's close this issue with the new ad-blocklist (I think I will try it with a wildcard-pattern for *.googlevideo.com instead). Thanks you nevertheless for your quick answer and help! 👍🏻
