### ISSUE TITLE
Facebook list

### ISSUE THREAD

**Issue by JacobOB1234** [d43m0nhLInt3r/socialblocklists#33]
One of the domains on the Facebook block list is breaking Instagram. I'd assume it's probably 0.0.0.0 instagram.c10r.facebook.com

**Comment by d43m0nhLInt3r** [comment]
I have now removed the url. I would be happy about your feedback whether it works now.

**Comment by d43m0nhLInt3r** [comment]
I have now investigated and it works for me now after taking out a few URLs

**Comment by JacobOB1234** [comment]
Yeah It's working for me again aswell
