### ISSUE TITLE
CNAMEs for skyapi.onedrive.live.com break OneDrive

### ISSUE THREAD

**Issue by p1r473** [d43m0nhLInt3r/socialblocklists#43]
![image](https://user-images.githubusercontent.com/9235633/140823603-ee9ec6c8-b1b2-4ec1-9234-39c5c5298a01.png)

i-am3p-cor001.api.p001.1drv.com
i-am3p-cor002.api.p001.1drv.com
i-am3p-cor003.api.p001.1drv.com
i-am3p-cor004.api.p001.1drv.com
i-am3p-cor005.api.p001.1drv.com
i-bl6p-cor001.api.p001.1drv.com
i-bl6p-cor002.api.p001.1drv.com
i-bn3p-cor001.api.p001.1drv.com
i-bn3p-cor090.api.p001.1drv.com
i-by3p-cor001.api.p001.1drv.com
i-by3p-cor002.api.p001.1drv.com
i-ch1-cor001.api.p001.1drv.com
i-ch1-cor002.api.p001.1drv.com
i-db3p-cor001.api.p001.1drv.com
i-db3p-cor002.api.p001.1drv.com
i-db3p-cor003.api.p001.1drv.com
i-db3p-cor004.api.p001.1drv.com
i-db3p-cor005.api.p001.1drv.com
i-sn2-cor001.api.p001.1drv.com
i-sn2-cor002.api.p001.1drv.com
i-sn3p-cor001.api.p001.1drv.com
i-sn3p-cor002.api.p001.1drv.com
ch1-cor001.api.p001.1drv.com
ch1-cor002.api.p001.1drv.com
bn2b-cor001.api.p001.1drv.com
bn2b-cor002.api.p001.1drv.com
bn2b-cor003.api.p001.1drv.com
bn2b-cor004.api.p001.1drv.com
bn2wns1.wns.windows.com
bn3p-cor001.api.p001.1drv.com
bn3sch020010558.wns.windows.com
bn3sch020010560.wns.windows.com
bn3sch020010618.wns.windows.com
bn3sch020010629.wns.windows.com
bn3sch020010631.wns.windows.com
bn3sch020010635.wns.windows.com
bn3sch020010636.wns.windows.com
bn3sch020010650.wns.windows.com
bn3sch020011727.wns.windows.com
bn3sch020012850.wns.windows.com
bn3sch020020322.wns.windows.com
bn3sch020020749.wns.windows.com
bn3sch020022328.wns.windows.com
bn3sch020022335.wns.windows.com
bn3sch020022361.wns.windows.com
bn4sch101120814.wns.windows.com
bn4sch101120818.wns.windows.com
bn4sch101120911.wns.windows.com
bn4sch101120913.wns.windows.com
bn4sch101121019.wns.windows.com
bn4sch101121109.wns.windows.com
bn4sch101121118.wns.windows.com
bn4sch101121223.wns.windows.com
bn4sch101121407.wns.windows.com
bn4sch101121618.wns.windows.com
bn4sch101121704.wns.windows.com
bn4sch101121709.wns.windows.com
bn4sch101121714.wns.windows.com
bn4sch101121908.wns.windows.com
bn4sch101122117.wns.windows.com
bn4sch101122310.wns.windows.com
bn4sch101122312.wns.windows.com
bn4sch101122421.wns.windows.com
bn4sch101123108.wns.windows.com
bn4sch101123110.wns.windows.com
bn4sch101123202.wns.windows.com
bn4sch102110124.wns.windows.com

**Comment by d43m0nhLInt3r** [comment]
I need the name of the blocklist. Thanks in advance

**Comment by p1r473** [comment]
/Tracking/trackingblocklist.txt

**Comment by d43m0nhLInt3r** [comment]
has to be tested
