### ISSUE TITLE
storage.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [d43m0nhLInt3r/socialblocklists#8]
Hi,
This breaks Google Drive.
This is in Tracking/trackingblocklist.txt

**Comment by dragonchaser** [comment]
It is also causing issues when working with kubernetes....

**Comment by d43m0nhLInt3r** [comment]
[fixed it](https://github.com/d43m0nhLInt3r/socialblocklists/commit/39085570d0f70b27a2823d290ce6b2d09e59e574) thanks for your help
